# Generated by Django 5.0.4 on 2024-05-09 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_object', models.CharField(blank=True, choices=[('car', 'авто'), ('door', 'дверь'), ('garage', 'гараж'), ('safe', 'сейф'), ('door_lock', 'дверной замок')], default='door_lock', help_text='Вид объекта', max_length=20)),
                ('service', models.CharField(blank=True, choices=[('replace', 'замена'), ('repair', 'ремонт'), ('open_lock', 'вскрытие'), ('install', 'установка'), ('hacking', 'взлом'), ('additional_services', 'дополнительные услуги'), ('repair_dop', 'доп-ремонт')], help_text='Вид услуги', max_length=25)),
                ('character', models.TextField(help_text='Введите услугу', verbose_name='Услуга')),
                ('price', models.IntegerField(default='7')),
            ],
            options={
                'ordering': ['lock_object'],
                'indexes': [models.Index(fields=['lock_object'], name='UnLock_lock_lock_ob_600b5e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='UnLock.locked')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
