# Generated by Django 5.0.4 on 2024-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnLock', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='lock_object',
            field=models.CharField(blank=True, choices=[('car', 'авто'), ('door', 'дверь'), ('garage', 'гараж'), ('safe', 'сейф'), ('door_lock', 'дверной замок')], default='door_lock', help_text='Вид объекта', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.CharField(blank=True, choices=[('replace', 'замена'), ('repair', 'ремонт'), ('open_lock', 'вскрытие'), ('install', 'установка'), ('hacking', 'взлом'), ('additional_services', 'дополнительные услуги'), ('repair_dop', 'доп-ремонт')], help_text='Вид услуги', max_length=25),
        ),
    ]
