# Generated by Django 5.0.4 on 2024-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnLock', '0003_review_lock_object_review_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePerKm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='locked',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=6),
        ),
    ]
